const express = require("express")
const {getmemberdetails, deleteMember,getmemberbyID,updatemember,getmemberdetailss,getmemberDetailBytrainer} = require("../controller/addmember")
const router=  express.Router()
router.post("/getmembers",getmemberdetails)
router.post("/deletemember",deleteMember)
router.post("/getmemberbyid",getmemberbyID)
router.post("/updatemember",updatemember)
router.post("/getmemberss",getmemberdetailss)
router.post("/getmemberbyTrainer",getmemberDetailBytrainer)
module.exports = router